name: Run Tests/Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: npm ci
      - name: Run lint
        run: npm run lint
